# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C5imoLP2bhfaS3nzHbNlptNQ9tyWPh2m
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

data=pd.read_csv('Realestate.csv')
data.head()

data.dropna(inplace=True)
data.head()

data["X1 transaction date"]=data["X1 transaction date"].astype(int)

data.corrwith(data['Y house price of unit area'])



import matplotlib.pyplot as plt
import seaborn as sns
plt.scatter(x=data['X1 transaction date'],y=data['Y house price of unit area'])
sns.boxplot(x=data['X1 transaction date'],y=data['Y house price of unit area'])


x=data.drop(['No','X1 transaction date','Y house price of unit area'],axis=1)
x.head(1)
y=data['Y house price of unit area']

model=LinearRegression()
model.fit(x,y)
import pickle
filename = 'abc.pkl'
pickle.dump(model, open(filename, 'wb'))